a = open("hello.txt",'w')
a.write("I Love LetsUpgrade")
a.close()
a = open("hello.txt",'r')
content = a.read()
a.close()
print(content)
a = open("hello.txt",'a')
a.write("\n This is my first file handling script......")
a.close()
